 rem I LOVE U REPLIKA

 playfield:
.XXX....X...XXX.X.X.XXX...X.X........
..X.....X...X.X.X.X.X.....X.X........
..X.....X...X.X.X.X.XX....X.X........
..X.....X...X.X.X.X.X.....X.X........
.XXX....XXX.XXX..X..XXX...XXX........
.....................................
..XX..XXX.XXX.X...XXX.X.X..X.........
..X.X.X...X.X.X....X..X.X.X.X........
..X.X.XX..XXX.X....X..XX..XXX........
..XX..X...X...X....X..X.X.X.X........
..X.X.XXX.X...XXX.XXX.X.X.X.X........
end

 COLUPF = 23
 COLUBK = 2

mainloop
 drawscreen
 score = score + 1
 goto mainloop

